#ifndef __G3507_HW_CONFIG_H
#define __G3507_HW_CONFIG_H

#include "LED.h"
#include "KEY.h"
#include "My_I2c.h"
#include "My_SPI.h"
#include "pwm.h"
#include "usart.h"
#include "tim.h"
#include "adc.h"
#include "ti/driverlib/dl_gpio.h"

/*
 * G3507_hw_config.h
 * 只维护实际用到的端口/引脚/IOMUX，注册和查找都在这里完成。
 */

/* LED 板级映射 */
#define G3507_LED1_IOMUX  IOMUX_PINCM50
#define HW_LED_MAP(X) \
    X(LED1, GPIOB, DL_GPIO_PIN_22)

/* KEY 板级映射：KEY1 = PB21，低电平按下。 */
#define G3507_KEY1_IOMUX IOMUX_PINCM49
#define HW_KEY_MAP(X) \
    X(KEY1, GPIOB, DL_GPIO_PIN_21)

/* USART0 板级映射（TX=PA10, RX=PA11） */
#define HW_USART0_TX_PORT GPIOA
#define HW_USART0_TX_PIN  DL_GPIO_PIN_10
#define HW_USART0_RX_PORT GPIOA
#define HW_USART0_RX_PIN  DL_GPIO_PIN_11

#define G3507_USART0_TX_IOMUX IOMUX_PINCM21
#define G3507_USART0_TX_FUNC  IOMUX_PINCM21_PF_UART0_TX
#define G3507_USART0_RX_IOMUX IOMUX_PINCM22
#define G3507_USART0_RX_FUNC  IOMUX_PINCM22_PF_UART0_RX

#define HW_USART_MAP(X) \
    X(API_USART1, API_USART_CORE_UART0, HW_USART0_TX_PORT, HW_USART0_TX_PIN, HW_USART0_RX_PORT, HW_USART0_RX_PIN)

/* TIM 板级映射：逻辑 API_TIM1 绑定到硬件 TIMG0。 */
#define HW_TIM_MAP(X) \
    X(API_TIM1, API_TIM_CORE_TIMG0)

/* PWM 板级映射：PA16 -> TIMA1 CCP1，PA17 -> TIMA1 CCP0。 */
#define G3507_PWM_TIMA1_CH1_PORT  GPIOA
#define G3507_PWM_TIMA1_CH1_PIN   DL_GPIO_PIN_16
#define G3507_PWM_TIMA1_CH1_IOMUX IOMUX_PINCM38
#define G3507_PWM_TIMA1_CH1_FUNC  IOMUX_PINCM38_PF_TIMA1_CCP1

#define G3507_PWM_TIMA1_CH0_PORT  GPIOA
#define G3507_PWM_TIMA1_CH0_PIN   DL_GPIO_PIN_17
#define G3507_PWM_TIMA1_CH0_IOMUX IOMUX_PINCM39
#define G3507_PWM_TIMA1_CH0_FUNC  IOMUX_PINCM39_PF_TIMA1_CCP0

#define HW_PWM_MAP(X) \
    X(API_PWM_TIM1, API_PWM_CH1, API_PWM_CORE_TIMA1, API_PWM_CORE_CCP0, G3507_PWM_TIMA1_CH0_PORT, G3507_PWM_TIMA1_CH0_PIN) \
    X(API_PWM_TIM1, API_PWM_CH2, API_PWM_CORE_TIMA1, API_PWM_CORE_CCP1, G3507_PWM_TIMA1_CH1_PORT, G3507_PWM_TIMA1_CH1_PIN)

/* ADC 板级映射*/
#define G3507_ADC0_CH2_PORT  GPIOA
#define G3507_ADC0_CH2_PIN   DL_GPIO_PIN_25
#define G3507_ADC0_CH2_IOMUX IOMUX_PINCM55

#define G3507_ADC1_CH5_PORT  GPIOB
#define G3507_ADC1_CH5_PIN   DL_GPIO_PIN_18
#define G3507_ADC1_CH5_IOMUX IOMUX_PINCM44

#define HW_ADC_MAP(X) \
    X(API_ADC1, API_ADC_CH2, G3507_ADC0_CH2_PORT, G3507_ADC0_CH2_PIN) \
    X(API_ADC2, API_ADC_CH5, G3507_ADC1_CH5_PORT, G3507_ADC1_CH5_PIN)

/* 软件 I2C1：SCL=PA1，SDA=PA0 */
#define HW_I2C1_SCL_PORT GPIOA
#define HW_I2C1_SCL_PIN  DL_GPIO_PIN_1
#define HW_I2C1_SCL_IOMUX IOMUX_PINCM2
#define HW_I2C1_SDA_PORT GPIOA
#define HW_I2C1_SDA_PIN  DL_GPIO_PIN_0
#define HW_I2C1_SDA_IOMUX IOMUX_PINCM1

/* 软件 I2C2：SCL=PB9，SDA=PB8 */
#define HW_I2C2_SCL_PORT GPIOB
#define HW_I2C2_SCL_PIN  DL_GPIO_PIN_9
#define HW_I2C2_SCL_IOMUX IOMUX_PINCM26
#define HW_I2C2_SDA_PORT GPIOB
#define HW_I2C2_SDA_PIN  DL_GPIO_PIN_8
#define HW_I2C2_SDA_IOMUX IOMUX_PINCM25

/* I2C 板级映射：注册 2 路软件 I2C。 */
#define HW_I2C_MAP(X) \
    X(My_I2C1, HW_I2C1_SCL_PORT, HW_I2C1_SCL_PIN, HW_I2C1_SDA_PIN) \
    X(My_I2C2, HW_I2C2_SCL_PORT, HW_I2C2_SCL_PIN, HW_I2C2_SDA_PIN)

/* 软件 SPI1：SCK=PB9，MOSI=PB8，MISO=PB7，CS=PB14 */
#define HW_SPI1_SCK_PORT  GPIOB
#define HW_SPI1_SCK_PIN   DL_GPIO_PIN_9
#define HW_SPI1_SCK_IOMUX IOMUX_PINCM26

#define HW_SPI1_MOSI_PORT GPIOB
#define HW_SPI1_MOSI_PIN  DL_GPIO_PIN_8
#define HW_SPI1_MOSI_IOMUX IOMUX_PINCM25

#define HW_SPI1_MISO_PORT GPIOB
#define HW_SPI1_MISO_PIN  DL_GPIO_PIN_7
#define HW_SPI1_MISO_IOMUX IOMUX_PINCM24

#define HW_SPI1_CS_PORT   GPIOB
#define HW_SPI1_CS_PIN    DL_GPIO_PIN_14
#define HW_SPI1_CS_IOMUX  IOMUX_PINCM31

/* SPI 板级映射：注册 1 路软件 SPI。 */
#define HW_SPI_MAP(X) \
        X(My_SPI1, HW_SPI1_CS_PORT, HW_SPI1_CS_PIN, \
            HW_SPI1_SCK_PORT, HW_SPI1_SCK_PIN, \
            HW_SPI1_MOSI_PORT, HW_SPI1_MOSI_PIN, \
            HW_SPI1_MISO_PORT, HW_SPI1_MISO_PIN)

/* OLED SPI 控制引脚定义：DC=PB11，RES=PB10 */
#define HW_OLED_DC_PORT  GPIOB
#define HW_OLED_DC_PIN   DL_GPIO_PIN_11
#define HW_OLED_DC_IOMUX IOMUX_PINCM28

#define HW_OLED_RES_PORT  GPIOB
#define HW_OLED_RES_PIN   DL_GPIO_PIN_10
#define HW_OLED_RES_IOMUX IOMUX_PINCM27

/* OLED SPI 控制引脚映射：注册 1 组 DC/RES。 */
#define HW_OLED_SPI_CTRL_MAP(X) \
	X(HW_OLED_DC_PORT, HW_OLED_DC_PIN, HW_OLED_RES_PORT, HW_OLED_RES_PIN)

#define HW_LED_COUNT    1U
/* 当前板子上注册了 1 个按键 */
#define HW_KEY_COUNT    1U
/* 当前板子上注册了 1 路 USART */
#define HW_USART_COUNT  1U
/* 当前板子上注册了 1 路 PWM（2 个输出通道） */
#define HW_PWM_COUNT    2U
/* 当前板子上注册了 1 路 TIM */
#define HW_TIM_COUNT    1U

/* 当前板子上注册了 1 路 ADC */
#define HW_ADC_COUNT  2U
/* 当前板子上注册了 2 路软件 I2C */
#define HW_I2C_COUNT  2U
/* 当前板子上注册了 1 路软件 SPI */
#define HW_SPI_COUNT  1U
/* 当前板子上注册了 1 组 OLED SPI 控制引脚 */
#define HW_OLED_SPI_CTRL_COUNT  1U

#endif /* __G3507_HW_CONFIG_H */
